/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/[_]shell'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as WorksSlugRouteImport } from './routes/works/$slug'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  path: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/_shell': typeof ShellRoute
  '/news/$slug': typeof NewsSlugRoute
  '/works/$slug': typeof WorksSlugRoute
  '/company/': typeof CompanyIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/members/': typeof MembersIndexRoute
  '/news/': typeof NewsIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/_shell': typeof ShellRoute
  '/news/$slug': typeof NewsSlugRoute
  '/works/$slug': typeof WorksSlugRoute
  '/company': typeof CompanyIndexRoute
  '/contact': typeof ContactIndexRoute
  '/members': typeof MembersIndexRoute
  '/news': typeof NewsIndexRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/_shell': typeof ShellRoute
  '/news/$slug': typeof NewsSlugRoute
  '/works/$slug': typeof WorksSlugRoute
  '/company/': typeof CompanyIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/members/': typeof MembersIndexRoute
  '/news/': typeof NewsIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_shell'
    | '/news/$slug'
    | '/works/$slug'
    | '/company/'
    | '/contact/'
    | '/members/'
    | '/news/'
    | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_shell'
    | '/news/$slug'
    | '/works/$slug'
    | '/company'
    | '/contact'
    | '/members'
    | '/news'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/news/$slug'
    | '/works/$slug'
    | '/company/'
    | '/contact/'
    | '/members/'
    | '/news/'
    | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  ShellRoute: typeof ShellRoute
  NewsSlugRoute: typeof NewsSlugRoute
  WorksSlugRoute: typeof WorksSlugRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: '/_shell'
      fullPath: '/_shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  ShellRoute: ShellRoute,
  NewsSlugRoute: NewsSlugRoute,
  WorksSlugRoute: WorksSlugRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
